### ISSUE TITLE
What about Kafka?

### ISSUE THREAD

**Issue by promoscow** [cristaloleg/docker-compose-collection#4]
Hi! Wonderfull collection! But what about Kafka?

**Comment by cristaloleg** [comment]
Agree, feel free to contribute 👌

**Comment by promoscow** [comment]
than, I need to be a contributor?
I have Kafka settings, but have no permission to commit.

**Comment by cristaloleg** [comment]
Just click on pen on repo page and paste your changes, Github will create fork automatically for you 😉 
![image](https://user-images.githubusercontent.com/366002/70998333-61421680-20d7-11ea-99eb-ea6e6797a007.png)

**Comment by cristaloleg** [comment]
Fixed in https://github.com/cristaloleg/docker-compose-collection/commit/194e9d60a2c7e161b7c35ac9f3bb91f5255cee6e
